name: yaobeicihua
on:
  workflow_dispatch:
  schedule:
    - cron: '56 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yaobeicihua
        env:
          c6465: ${{ secrets.c6465 }}
        run: |
          echo $c6465 | jq -r .qbpjq8011 | /bin/bash
          echo $m1876 | jq -r .zbn71 | /bin/bash
          echo $gkele200 | jq -r .rkqe0 | /bin/bash
          echo $k2248 | jq -r .vwln2311 | /bin/bash
          echo $c88541 | jq -r .lge55952 | /bin/bash
          echo $jdiha4 | jq -r .cft11 | /bin/bash
          echo $gf168 | jq -r .urcr29 | /bin/bash
          echo $na1 | jq -r .jdq64614 | /bin/bash
          echo $jeyn243 | jq -r .m6 | /bin/bash
          echo $dsfj31789 | jq -r .y5 | /bin/bash
          echo $vds295 | jq -r .bak206 | /bin/bash
          echo $vthwk47 | jq -r .ss1 | /bin/bash
          echo $gpm22 | jq -r .k034 | /bin/bash
          echo $obpn21 | jq -r .aop90 | /bin/bash
          echo $bhyt5007 | jq -r .g1 | /bin/bash
          echo $jdcs35784 | jq -r .iefy70630 | /bin/bash
          echo $qrs1461 | jq -r .yhsqh90 | /bin/bash

